version: "3.7"


services:
  backup:
    build:
      context: .
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_ROOT_PWD: ${DATABASE_ROOT_PWD}
      DUMP_COMPRESS: ${DUMP_COMPRESS}
      S3_EXPIRE_TIME: ${S3_EXPIRE_TIME}
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION_NAME: ${S3_REGION_NAME}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      TZ: ${TZ}
